POST http://localhost:3333/lms/courses
Content-Type: application/json
###

GET http://localhost:3333/curso/nodejs-fundamentos


###


GET http://localhost:3333/lms/courses


###

GET http://localhost:3333/lms/course/javascript-completo

###

GET http://localhost:3333/lms/lesson/javascript-completo/introducao-e-variaveis