POST http://localhost:3333/lms/courses
Content-Type: application/json
###

GET http://localhost:3333/curso/nodejs-fundamentos


###


GET http://localhost:3333/lms/courses


###

GET http://localhost:3333/lms/course/javascript-completo

###
GET http://localhost:3333/lms/course/nodejs-do-zero-ao-avancado

###

GET http://localhost:3333/lms/lesson/javascript-completo/fetch-e-async-await

###
GET http://localhost:3333/lms/lesson/nodejs-do-zero-ao-avancado/introducao-ao-nodejs
###

POST http://localhost:3333/lms/lesson/complete
Content-Type: application/json

{
  "courseId": 4,
  "lessonId": 13
}

### 
DELETE  http://localhost:3333/lms/course/reset
Content-Type: application/json

{
 "courseId": 4
}

###

GET http://localhost:3333/lms/certificates
###

GET http://localhost:3333/lms/certificate/4c940bd80992c4a8